export * from './product-id.vo';
export * from './product-name.vo';
export * from './product-slug.vo';
export * from './product-sku.vo';
export * from './product-description.vo';
export * from './product-status.vo';
export * from './product-image.vo';
export * from './product-model-3d.vo';
export * from './image-id.vo';
